openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Get Users'
  description: Get the contributors of the repo

paths:
  /users/{userID}:
    parameters:
      - name: userID
        description: The unique identifier of the User
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
    get:
      summary: users by id
      responses:
        '200':
          description: The User corresponding to the `userID`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    userID:
      description: The unique identifier of a User
      type: string
    User:
      type: string
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/userID'
        name:
          type: string
        type:
          type: string
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Error please try again
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []